[package]
name = "imgui-ui"
version = "0.1.0"
edition.workspace = true
authors = ["Sascha Willems <webmaster@saschawillems.de>"]

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { workspace = true }