[package]
name = "hdr-bloom"
version = "0.1.0"
edition.workspace = true

[dependencies]
spirv-std = { workspace = true }

[lib]
crate-type = ["dylib"]

[features]
default = []

[package.metadata.rust-gpu.build]
capabilities = ["ImageQuery"]