[package]
name = "geometryshader-normaldebug"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { workspace = true }

[package.metadata.rust-gpu.build]
capabilities = ["Geometry"]