[package]
name = "prefilterenvmap"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { workspace = true }

[package.metadata.rust-gpu.build]
capabilities = ["ImageQuery"]