[workspace]
resolver = "2"
members = [
    "triangle",
    "pushconstants",
    "base/uioverlay",
]

[workspace.dependencies]
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu.git", branch = "main" }
bytemuck = { version = "1.14", features = ["derive"] }

[profile.release]
panic = "abort"
opt-level = 3
