[workspace]
resolver = "2"
members = [
    "triangle",
    "pushconstants",
    "descriptorsets/cube",
    "dynamicuniformbuffer/base",
    "multisampling/mesh",
    "texture",
    "pipelines/phong",
    "pipelines/toon",
    "pipelines/wireframe",
    "specializationconstants/uber",
    "computeshader/edgedetect",
    "computeshader/emboss",
    "computeshader/sharpen",
    "computeshader/texture",
    "texturearray/instancing",
    "base/uioverlay",
    "base/textoverlay", "gears", "screenshot/mesh",
]

[workspace.dependencies]
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu.git", branch = "main" }
bytemuck = { version = "1.14", features = ["derive"] }

[profile.release]
panic = "abort"
opt-level = 3
