[package]
name = "gaussblur"
version = "0.1.0"
edition = "2021"

[dependencies]
spirv-std = { workspace = true }
bytemuck = { workspace = true }

[lib]
crate-type = ["dylib"]

[package.metadata.rust-gpu.build]
capabilities = ["ImageQuery"]
